*==============================
* Localization strings
*==============================

* Captions

#define ccLOC_CAP_MEMBER_DATA_EDITOR	'MemberData Editor'
#define ccLOC_CAP_HAS_MEMBER_DATA		'\<Has MemberData'
#define ccLOC_CAP_OVERRIDE				'O\<verride:'
#define ccLOC_CAP_FAVORITES				'\<Favorites:'
#define ccLOC_CAP_DISPLAY				'\<Display as:'
#define ccLOC_CAP_SCRIPT				'Sc\<ript:'
#define ccLOC_CAP_OK					'OK'
#define ccLOC_CAP_CANCEL				'Cancel'
#define ccLOC_CAP_FILTER				'F\<ilter:'
#define ccLOC_CAP_HUNGARIAN_NAMES		'Use \<Hungarian names for properties'
#define ccLOC_CAP_METHOD_PREFIXES		'Method prefi\<xes:'
#define ccLOC_CAP_DISPLAY_DEFAULTS		'Display As defaults'
#define ccLOC_CAP_OTHER_OPTIONS			'Other options'
#define ccLOC_CAP_ADD_CR				'\<Line break after each XML element'
#define ccLOC_CAP_SCRIPT_FONT			'\<Script font...'
#define ccLOC_CAP_SETTINGS_PAGE			'\<Settings'
#define ccLOC_CAP_USER_PAGE				'\<User-Defined'
#define ccLOC_CAP_OPTIONS				'O\<ptions...'
#define ccLOC_CAP_VIEW_XML				'View \<XML...'
#define ccLOC_CAP_HIERARCHY				'Hi\<erarchy...'
#define ccLOC_CAP_MEMBER_DATA_OPTIONS	'MemberData Editor Options'
#define ccLOC_CAP_INSTRUCTIONS			'Select the member from the list, choose the desired scope, and set the MemberData settings as desired. Members with an icon have MemberData set at some level. Members in bold have MemberData set at selected scope.'
#define ccLOC_CAP_SCOPE_OBJECT			'\<Object'
#define ccLOC_CAP_SCOPE_CONTAINER		'\<Container:'
#define ccLOC_CAP_SCOPE_GLOBAL			'\<Global'
#define ccLOC_CAP_ADD					'\<Add...'
#define ccLOC_CAP_REMOVE				'\<Remove'
#define ccLOC_CAP_VALUE					'\<Value:'
#define ccLOC_CAP_ATTRIBUTE				'A\<ttribute:'
#define ccLOC_CAP_CREATE_PROPERTY		'\<Automatically add _MemberData property to objects'

#define ccLOC_CAP_Vis_Protected			'Protected'
#define ccLOC_CAP_Vis_Hidden			'Hidden'
#define ccLOC_STR_PUBLIC				'Public'

* StatusBarText/ToolTipText values

#define ccLOC_TT_HAS_MEMBER_DATA		'Specifies whether this member has MemberData'
#define ccLOC_TT_OVERRIDE				'Specifies whether the default behavior should be used for unspecified attributes'
#define ccLOC_TT_FAVORITES				'Specifies whether this member appears on the Favorites tab of the Properties window'
#define ccLOC_TT_DISPLAY				'The name displayed for this member in the Properties window and IntelliSense'
#define ccLOC_TT_SCRIPT					'The code to execute as the property editor for this member'
#define ccLOC_TT_SCRIPT_ZOOM			'Zoom to a larger window'
#define ccLOC_TT_FILTER					'Filters the member list'
#define ccLOC_TT_HUNGARIAN_NAMES		'If this setting is turned on, the default capitalization for the Display As setting is the first letter in lower case and the rest of the name in proper case'
#define ccLOC_TT_METHOD_PREFIXES		'Enter a comma-delimited list of prefixes for method names with the capitalization to use as a default for these names (for example, a prefix of "Has" means the Display As setting for the "hasmembers" method would default to "HasMembers")'
#define ccLOC_TT_DISPLAY_DEFAULTS		'Specifies how the default Display As setting is determined'
#define ccLOC_TT_OTHER_OPTIONS			'Specify other settings'
#define ccLOC_TT_ADD_CR					'If this setting is turned on, a line break is added after each element in the XML'
#define ccLOC_TT_SCRIPT_FONT			'Specifies the font to use for the Script editbox'
#define ccLOC_TT_OPTIONS				'Displays the MemberData Editor Options dialog'
#define ccLOC_TT_VIEW_XML				'Displays the MemberData XML contents'
#define ccLOC_TT_HIERARCHY				'Displays how the MemberData is set for the selected member at each level of the class, containership, and global hierarchy'
#define ccLOC_TT_SCOPE_OBJECT			'Displays MemberData set in the selected object'
#define ccLOC_TT_SCOPE_CONTAINER		'Displays MemberData set in the containership hierarchy'
#define ccLOC_TT_SCOPE_GLOBAL			'Displays MemberData set globally in FoxCode.dbf'
#define ccLOC_TT_ADD					'Adds a custom attribute to the MemberData for the selected member'
#define ccLOC_TT_REMOVE					'Removes the selected custom attribute from the MemberData for the selected member'
#define ccLOC_TT_LISTVIEW				'Double-click to toggle the Has MemberData setting'
#define ccLOC_TT_VALUE					'Specify the value for the selected custom attribute'
#define ccLOC_TT_CUSTOM_LIST			'Select a custom attribute to update its value or remove it'
#define ccLOC_TT_CREATE_PROPERTY		'If this setting is turned on, a record is added to your IntelliSense (FOXCODE) table that automatically creates a _MemberData property for a form opened in the Form Designer or the outer-most object in the Class Designer'

* Messages

#define ccLOC_STRING_TOO_LONG			'The MemberData for this class is over 8K in size, which is too long. You will have to remove some MemberData attributes before this can be saved.'
#define ccLOC_INVALID_DISPLAY			'Display As can only differ from the member name in capitalization.'
#define ccLOC_INVALID_XML				'The _MemberData property of this object contains invalid XML.'
#define ccLOC_EDITOR_REGISTERED			'The MemberData Editor has been registered.'
#define ccLOC_CANT_OPEN_FOXCODE			'The FoxCode table could not be opened.'
#define ccLOC_NO_QUOTES					'You cannot enter double quotes in the script.'
#define ccLOC_BAD_FILTER				'There are no members that match the selected filter, so all members will be displayed.'
#define ccLOC_USE_PARENT				'The selected object does not have an _MemberData property, so its MemberData cannot be edited with the MemberData Editor. You may edit the MemberData at the container or global level.'
#define ccLOC_CANT_ADD_FAVORITES		'The selected object does not have an _MemberData property, so the selected member cannot be added to Favorites using the Add to Favorites function. Instead, use the MemberData Editor to add this member to Favorites at the desired containership level.'
#define ccLOC_ALL_MEMBERS				'All members'
#define ccLOC_CUSTOM_MEMBERS			'Custom members only'
#define ccLOC_CUSTOM_IN_CLASS			'Custom members added in this class'
#define ccLOC_NATIVE_MEMBERS			'Native members only'
#define ccLOC_FAVORITE_MEMBERS			'Favorites only'
#define ccLOC_NO_MEMBERDATA				'There is no MemberData defined in this object.'
#define ccLOC_NO_MEMBERDATA_FOR_PEM		'There is no MemberData defined for this member.'
#define ccLOC_IN_THIS_OBJECT			'in this object'
#define ccLOC_IN_PARENT_CLASS			'in a parent class'
#define ccLOC_IN_CONTAINER				'in a container'
#define ccLOC_IN_GLOBAL					'globally'
#define ccLOC_ATTRIBUTE_SET				'The current setting for <Insert> is set'
#define ccLOC_OF						' of '
#define ccLOC_LEVEL_CLASS				'Class'
#define ccLOC_LEVEL_CONTAINER			'Container'
#define ccLOC_LEVEL_GLOBAL				'Global'
#define ccLOC_EFFECTIVE_SETTINGS		'Effective settings:'
#define ccLOC_TRUE						'True'
#define ccLOC_FALSE						'False'
#define ccLOC_CUSTOM_NAME				'Attribute name'
#define ccLOC_ADD_CUSTOM				'Add Custom Attribute'
#define ccLOC_BAD_CUSTOM_NAME			'That is not a valid name for a custom attribute. Names must consists of only characters, digits, or underscores, and must not start with a digit.'
#define ccLOC_CUSTOM_NAME_EXIST			'There is already a custom attribute with that name.'
#define ccLOC_CONFIRM_REMOVE_CUSTOM		'Remove this custom attribute?'
#define ccLOC_BAD_CALL					'The MemberData Editor should be invoked from the Form or Class menus or as the property editor for the _MemberData property. You can also DO MemberDataEditor.APP with no parameters to register it.'

#Define ccLOC_File_Not_Found      			'***** Warning *****' + ccCR + 'Class Library <FileName> not found' + ccCR + '  .... Continuing'
#Define ccLOC_MEM_CAP_TITLE			'PEM Editor'

